### ISSUE TITLE
Using the model

### ISSUE THREAD

**Issue by angoodkind** [ZagHe568/speak-turn-emb-dialog-act-clf#2]
Do you have an example of using one of the trained models to test new sentences?

**Comment by zihaohe123** [comment]
Hi,

Thanks for your interest!

I'll create a formal example next week. If you don't wanna wait, here is what you can do.

1. Uncomment line 91-92 in engine.py. Run the code with one of the three datasets that you think are most similar to your dataset.
2. Comment line 68-92. Above line 93, add self.model.load_state_dict(torch.load('ckp/model.pt'))
3. Prepare your own dataset as described in "Train the model on other datasets" in README.md. If you don't have training data and validation data, just put train.csv and val.csv as two empty dataframes, with the required columns.
4. Run the code on your dataset. The hyperparamters "nlayer" and "nfinetune" should be the same as in step 1.

Best,
Zihao

**Comment by angoodkind** [comment]
Thanks so much! I will also play around with the directions above.

**Comment by angoodkind** [comment]
Hi - Just following up on this. Thanks!

**Comment by zihaohe123** [comment]
Hi! Thanks for the reminder! Will do it tomorrow

**Comment by zihaohe123** [comment]
Please pull the newer code and follow the instructions in README.md

**Comment by angoodkind** [comment]
Sorry for the delayed response. My code is starting to run well, but I don't think I have enough computer power for training. Is a pretrained model available?

**Comment by angoodkind** [comment]
Hi Zihao,

When running inference mode, I get an error when tokenizing the validation set. Both `train.csv` and `val.csv` are empty csv files with these column headings:
```
speaker,text,act,conv_id,topic,topic_ldaconv,topic_ldautt

```
Below is the error. Is it related to [this issue](https://github.com/huggingface/transformers/issues/3091)?

```
% python run_my_thesis.py
python -u engine.py --corpus=my_thesis --mode=inference --gpu=0,1 --batch_size=2 --batch_size_val=2 --epochs=100 --lr=0.0001 --nlayer=2 --chunk_size=196 --dropout=0.5 --nfinetune=1 --speaker_info=emb_cls --topic_info=none --nclass=43 --emb_batch=0
Namespace(corpus='my_thesis', mode='inference', nclass=43, batch_size=2, batch_size_val=2, emb_batch=0, epochs=100, gpu='0,1', lr=0.0001, nlayer=2, chunk_size=196, dropout=0.5, speaker_info='emb_cls', topic_info='none', nfinetune=1, seed=0)
Tokenizing train....
Done
Tokenizing val....
Traceback (most recent call last):
  File "/Users/adamg/Dropbox/Dissertation-DB/Dissertation-Dialogue-Acts-Labels-ZHe/engine.py", line 190, in <module>
    engine = Engine(args)
  File "/Users/adamg/Dropbox/Dissertation-DB/Dissertation-Dialogue-Acts-Labels-ZHe/engine.py", line 26, in __init__
    val_loader = data_loader(corpus=args.corpus,
  File "/Users/adamg/Dropbox/Dissertation-DB/Dissertation-Dialogue-Acts-Labels-ZHe/datasets.py", line 142, in data_loader
    dataset = DialogueActData(corpus, phase, chunk_size=chunk_size)
  File "/Users/adamg/Dropbox/Dissertation-DB/Dissertation-Dialogue-Acts-Labels-ZHe/datasets.py", line 63, in __init__
    encodings_all = tokenizer(texts_all, truncation=True, padding=True)
  File "/Users/adamg/opt/miniconda3/envs/dialogue-acts/lib/python3.9/site-packages/transformers/tokenization_utils_base.py", line 2403, in __call__
    return self.batch_encode_plus(
  File "/Users/adamg/opt/miniconda3/envs/dialogue-acts/lib/python3.9/site-packages/transformers/tokenization_utils_base.py", line 2588, in batch_encode_plus
    return self._batch_encode_plus(
  File "/Users/adamg/opt/miniconda3/envs/dialogue-acts/lib/python3.9/site-packages/transformers/models/gpt2/tokenization_gpt2_fast.py", line 163, in _batch_encode_plus
    return super()._batch_encode_plus(*args, **kwargs)
  File "/Users/adamg/opt/miniconda3/envs/dialogue-acts/lib/python3.9/site-packages/transformers/tokenization_utils_fast.py", line 439, in _batch_encode_plus
    for key in tokens_and_encodings[0][0].keys():
IndexError: list index out of range
```

**Comment by zihaohe123** [comment]
Hi Adam,

Yes I can give you a pretrained model. but it seems I've lost the checkpoint. Need to retrain a model. Can give you one on Friday (PST).

Regarding the error, seems you need to put some random stuff in train.csv and val.csv, instead of making them both empty dataframes. Just put one row in both of them for now. Sorry for my wrong instructions! I'll update the code. Thanks for finding this error!

**Comment by angoodkind** [comment]
Thanks, that would be great!

I added dummy lines, but there are 2 issues:
1) If I run this on a CPU-only machine, I get an error. That's easy enough to fix, jut changing line 155 in engine.py to `self.model.load_state_dict(torch.load('ckp/model.pt', map_location=torch.device('cpu')))`

2) However, when running it on a GPU machine, I then get the following error:
```
python -u engine.py --corpus=my_thesis --mode=inference --gpu=0,1 --batch_size=2 --batch_size_val=2 --epochs=100 --lr=0.0001 --nlayer=2 --chunk_size=196 --dropout=0.5 --nfinetune=1 --speaker_info=emb_cls --topic_info=none --nclass=43 --emb_batch=0
Namespace(batch_size=2, batch_size_val=2, chunk_size=196, corpus='my_thesis', dropout=0.5, emb_batch=0, epochs=100, gpu='0,1', lr=0.0001, mode='inference', nclass=43, nfinetune=1, nlayer=2, seed=0, speaker_info='emb_cls', topic_info='none')
Tokenizing train....
Downloading: 100% 481/481 [00:00<00:00, 532kB/s]
Downloading: 100% 878k/878k [00:01<00:00, 828kB/s] 
Downloading: 100% 446k/446k [00:00<00:00, 505kB/s]
Downloading: 100% 1.29M/1.29M [00:01<00:00, 1.24MB/s]
Done
Tokenizing val....
Done
Tokenizing test....
Done
Done

Let's use 1 GPUs!
Initializing model....
Downloading: 100% 478M/478M [00:07<00:00, 67.6MB/s]
Some weights of the model checkpoint at roberta-base were not used when initializing RobertaModel: ['lm_head.decoder.weight', 'lm_head.layer_norm.weight', 'lm_head.bias', 'lm_head.dense.weight', 'lm_head.layer_norm.bias', 'lm_head.dense.bias']
- This IS expected if you are initializing RobertaModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing RobertaModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
/usr/local/lib/python3.7/dist-packages/transformers/optimization.py:309: FutureWarning: This implementation of AdamW is deprecated and will be removed in a future version. Use the PyTorch implementation torch.optim.AdamW instead, or set `no_deprecation_warning=True` to disable this warning
  FutureWarning,
Traceback (most recent call last):
  File "engine.py", line 194, in <module>
    engine.inference()
  File "engine.py", line 158, in inference
    self.eval(val=False, inference=True)
  File "engine.py", line 128, in eval
    for i, batch in enumerate(loader):
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/dataloader.py", line 521, in __next__
    data = self._next_data()
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/dataloader.py", line 561, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/content/drive/MyDrive/DAZHe/datasets.py", line 133, in __getitem__
    'topic_labels': torch.tensor(self.topic_labels[index], dtype=torch.long)
ValueError: cannot convert float NaN to integer
```

Where can I insert code that will delete rows with NaNs?

**Comment by ZagHe568** [comment]
when you trained the model, was it on CPU or GPU?

**Comment by zihaohe123** [comment]
did you prepare your test.csv correctly?

**Comment by zihaohe123** [comment]
It seems you don't have anything in your "topic" column.

**Comment by angoodkind** [comment]
I tried 2 solutions, but both end in the same error:
1) I populated the blank columns with 0s
2) I changed the `topic` column to `topic_labels`

This is what my train and val csv's look like. This is also the first entry in test.csv
```
speaker,text,act,conv_id,topic_labels,topic_ldaconv,topic_ldautt
2,Definitely check out The Golden Palace now streaming on Hulu! A perfect warm bath for your brain,0,E001,0,0,0
```

**Comment by zihaohe123** [comment]
change the column "topic_labels" to "topic". Refer to line 82 of datasets.py

**Comment by angoodkind** [comment]
That was what I had initially. I then populated the empty columns with 0s, but it still resulted in the same error.

**Comment by zihaohe123** [comment]
Look at line 52 in dataset.py. Make sure the program was processing the data from scratch instead of reading the cached pickle files. In that case delete the pickle files.

**Comment by angoodkind** [comment]
That did the trick! It may help to add all of these notes to the README. As an additional note, you also need to install scikit-learn for this to run.

**Comment by angoodkind** [comment]
Just wanted to send a reminder. Do you think it would be possible to generate the full model in the next few days? Thanks!

**Comment by zihaohe123** [comment]
Training the model. Will get back to you later today

**Comment by zihaohe123** [comment]
The checkpoint is here at https://drive.google.com/file/d/1VUY048dZTzMvnzKcpLK5_XhUYPDnswXq/view?usp=sharing
Note that this model is not the one reported in the paper.

**Comment by angoodkind** [comment]
Looks like it worked great! Thank you so much!
