### ISSUE TITLE
Size of the dictionary of embeddings

### ISSUE THREAD

**Issue by raresionut1** [ZagHe568/speak-turn-emb-dialog-act-clf#6]
In models.py, why are there 3 different embeddings for speakers instead of 2? I thought all the conversations are dyadic, hence there should be only 2 speaker tags --> 2 embeddings, right?

```
# making use of speaker info
self.speaker_emb = nn.Embedding(3, nhid) # why not 2?
```

**Comment by zihaohe123** [comment]
Hi Rares, thanks for your interest! The size doesn't matter, as we only update the first two embeddings. As long as the size is greater than 2 it should be fine.
